// ParrotTalk — SOURCE D'AUTORING Listening Test 03 (refonte v2 — simulateur fidèle)
// Contenu 100 % original. Même chaîne que Test 01 v2 : narration d'examen gravée,
// exemple Partie 1, coupures milieu (S1–3), Partie 4 d'un trait, cue sheets.
// Scripts vivants : remplissage naturel, digressions, distracteurs corrigés.
// Règle Porte 1 : ordre des réponses (`at`) strictement croissant.

const TEST03 = {
  id: 'test03',
  title: 'Listening Test 03',
  accentPool: ['en-GB', 'en-AU', 'en-US'],
  narratorVoice: 'en-GB-Neural2-D',
  intro: 'Welcome to your ultimate listening challenge, the ParrotTalk test. You will hear a number of different recordings, and you will hear each one only once.',
  sections: [

    // ── SECTION 1 — Dialogue transactionnel (form completion + épellation) ──────
    {
      number: 1,
      title: 'Meadowbank Community Hall — Event Booking',
      type: 'form',
      runtimeType: 'form', requiredTypes: ['completion'], wordLimit: 3,
      context: 'a telephone conversation between a man and a booking officer as he books a community hall for an event',
      splitAt: 12,
      example: {
        lines: [
          { who: 'officer', text: "Meadowbank Community Hall bookings, how can I help?" },
          { who: 'caller',  text: "Hello, I'd like to book the hall for an event next month, please." },
        ],
        answer: "The caller wants to book the hall for an event, so 'event' has been written in the space. Now we shall begin.",
      },
      formTitle: 'MEADOWBANK COMMUNITY HALL — BOOKING FORM · Q1–10',
      instructions: 'Write NO MORE THAN THREE WORDS AND/OR A NUMBER for each answer.',
      speakers: {
        officer: { voice: 'en-GB-Neural2-C', gender: 'F', accent: 'en-GB', label: 'Booking officer' },
        caller:  { voice: 'en-US-Neural2-D', gender: 'M', accent: 'en-US', label: 'Caller' },
      },
      script: [
        { who: 'officer', text: "Good morning, Meadowbank Community Hall bookings, this is Sandra speaking. How can I help?" },
        { who: 'caller',  text: "Hi, I'd like to book the hall for an event, and check a couple of things about what's included." },
        { who: 'officer', text: "Of course. Let's start with your surname?" },
        { who: 'caller',  text: "It's Hargreaves — that's H. A. R. G. R. E. A. V. E. S." },
        { who: 'officer', text: "Thank you. And what kind of event is it — a birthday, a meeting?" },
        { who: 'caller',  text: "It's a wedding reception, actually. We first thought a small birthday party, but it's grown into the wedding." },
        { who: 'officer', text: "Congratulations! And which date did you have in mind?" },
        { who: 'caller',  text: "The eighteenth of October. Not the eighth — the eighteenth." },
        { who: 'officer', text: "The eighteenth of October, noted. Roughly how many guests?" },
        { who: 'caller',  text: "About a hundred and twenty. We did say two hundred at first, but the list came down." },
        { who: 'officer', text: "A hundred and twenty. We have two spaces — the Main Hall and the Garden Room. Which would you prefer?" },
        { who: 'caller',  text: "The Garden Room sounds lovely, with the view." },
        { who: 'officer', text: "Lovely choice. And what time would you like to start?" },
        { who: 'caller',  text: "Let's say six p.m. — actually we said five earlier, but six gives us more time to set up." },
        { who: 'officer', text: "Six p.m., noted. Will you be using our in-house caterer, or arranging your own?" },
        { who: 'caller',  text: "We'll bring our own catering, thanks." },
        { who: 'officer', text: "No problem. Is there any equipment you'll need from us?" },
        { who: 'caller',  text: "Yes — a projector, for a slideshow. We've got our own microphone." },
        { who: 'officer', text: "A projector, noted. There's a deposit to secure the booking — for most events it's fifty pounds, but for weddings we ask for a hundred and fifty." },
        { who: 'caller',  text: "A hundred and fifty, that's fine." },
        { who: 'officer', text: "Great. Your booking reference is CH2291 — do keep that for any changes." },
        { who: 'caller',  text: "CH2291 — got it. Thank you, Sandra!" },
      ],
      questions: [
        { n: 1,  at: 3,  label: 'Surname',              answer: 'HARGREAVES',  alt: ['hargreaves'] },
        { n: 2,  at: 5,  label: 'Type of event',        answer: 'WEDDING',     alt: ['wedding reception'] },
        { n: 3,  at: 7,  label: 'Date',                 answer: '18 OCTOBER',  alt: ['eighteenth of october', '18 oct', 'oct 18'] },
        { n: 4,  at: 9,  label: 'Number of guests',     answer: '120',         alt: ['a hundred and twenty', 'one hundred twenty'] },
        { n: 5,  at: 11, label: 'Room booked',          answer: 'GARDEN ROOM', alt: ['garden room', 'the garden room'] },
        { n: 6,  at: 13, label: 'Start time',           answer: '6 PM',        alt: ['six', 'six pm', '6pm', '18:00'] },
        { n: 7,  at: 15, label: 'Catering',             answer: 'OWN',         alt: ['own catering', 'their own', 'bring their own'] },
        { n: 8,  at: 17, label: 'Equipment needed',     answer: 'PROJECTOR',   alt: ['a projector'] },
        { n: 9,  at: 18, label: 'Deposit (£)',          answer: '150',         alt: ['£150', 'a hundred and fifty', '150 pounds'] },
        { n: 10, at: 20, label: 'Booking reference',    answer: 'CH2291',      alt: ['ch 2291'] },
      ],
    },

    // ── SECTION 2 — Monologue informatif (map labelling + MCQ) ──────────────────
    {
      number: 2,
      title: 'Seabridge Aquarium — Visitor Briefing',
      type: 'mixed',
      runtimeType: 'mixed', requiredTypes: ['maplabel', 'mc'],
      context: 'a talk by a guide giving visitors a briefing at an aquarium',
      splitAt: 7,
      speakers: {
        guide: { voice: 'en-AU-Neural2-A', gender: 'F', accent: 'en-AU', label: 'Aquarium guide' },
      },
      script: [
        { who: 'guide', text: "G'day everyone, and welcome to Seabridge Aquarium. Before you explore, let me show you around using the map in your booklet, marked A to H." },
        { who: 'guide', text: "First, everyone's favourite — the touch pool, where you can gently handle starfish and crabs, is at point E, in the central hall." },
        { who: 'guide', text: "Our biggest attraction, the shark tank, is at point G. It was originally going to be at point A, but we moved it to the larger space at G." },
        { who: 'guide', text: "If you need a break, the café is at point C, upstairs, overlooking the main tank." },
        { who: 'guide', text: "The cloakroom, for bags and coats, is at point B, just by the entrance." },
        { who: 'guide', text: "And on your way out, the gift shop is at point H, right next to the exit." },
        { who: 'guide', text: "Now, a few practical things worth knowing before you set off." },
        { who: 'guide', text: "We're open every day, but do note we close early on Mondays — four p.m., not the usual six." },
        { who: 'guide', text: "The most popular event is the penguin feeding, at eleven thirty each morning. The seals are fed later, at two." },
        { who: 'guide', text: "Photography is welcome, but please, no flash near the tanks — it distresses the animals." },
        { who: 'guide', text: "If you visit often, our annual membership pays for itself in about three visits, and it includes a café discount." },
        { who: 'guide', text: "Finally, for safety: please don't lean over the open tanks, and keep small children holding an adult's hand." },
        { who: 'guide', text: "Right — enjoy Seabridge, and mind the splash zone!" },
      ],
      groups: [
        {
          type: 'form', kind: 'maplabel',
          formTitle: 'SEABRIDGE AQUARIUM — MAP · Q11–15',
          instructions: 'Label the map below. Write the correct letter, A–H, next to each place.',
          questions: [
            { n: 11, at: 1, label: 'Touch pool',  answer: 'E', alt: ['e'] },
            { n: 12, at: 2, label: 'Shark tank',  answer: 'G', alt: ['g'] },
            { n: 13, at: 3, label: 'Café',        answer: 'C', alt: ['c'] },
            { n: 14, at: 4, label: 'Cloakroom',   answer: 'B', alt: ['b'] },
            { n: 15, at: 5, label: 'Gift shop',   answer: 'H', alt: ['h'] },
          ],
        },
        {
          type: 'mc',
          instructions: 'Choose the correct letter, A, B or C.',
          questions: [
            { n: 16, at: 7,  text: 'On which day does the aquarium close early?',
              options: ['Sunday', 'Monday', 'Friday'], answer: 1, anchor: ['mondays', 'monday'] },
            { n: 17, at: 8,  text: 'What time does the penguin feeding take place?',
              options: ['10:30', '11:30', '2:00'], answer: 1, anchor: ['eleven thirty'] },
            { n: 18, at: 9,  text: 'What is the rule about photography?',
              options: ['No photos at all', 'No flash near the tanks', 'No phones'], answer: 1, anchor: ['no flash', 'flash'] },
            { n: 19, at: 10, text: 'What does annual membership include?',
              options: ['Free parking', 'A café discount', 'A free gift'], answer: 1, anchor: ['café discount', 'discount'] },
            { n: 20, at: 11, text: 'What is the main safety instruction?',
              options: ['Wear a wristband', "Don't lean over the tanks", 'Stay with a guide'], answer: 1, anchor: ['lean over', 'lean'] },
          ],
        },
      ],
    },

    // ── SECTION 3 — Discussion académique 3 locuteurs (MCQ + matching + completion)
    {
      number: 3,
      title: 'Tutorial — Geography Field Trip Planning',
      type: 'discussion',
      runtimeType: 'mixed', requiredTypes: ['mc', 'matching', 'completion'],
      context: 'a discussion between a tutor and two students planning a geography field trip',
      splitAt: 10,
      speakers: {
        tutor: { voice: 'en-GB-Neural2-B', gender: 'M', accent: 'en-GB', label: 'Dr Okafor (tutor)' },
        nadia: { voice: 'en-US-Neural2-E', gender: 'F', accent: 'en-US', label: 'Nadia (student)' },
        sam:   { voice: 'en-AU-Neural2-D', gender: 'M', accent: 'en-AU', label: 'Sam (student)' },
      },
      script: [
        { who: 'tutor', text: "Right, Nadia, Sam — let's plan your geography field trip. Have you settled on where you're going?" },
        { who: 'nadia', text: "Yes. We were tempted by the coast, but we've decided on the river valley instead — there's much more to measure there." },
        { who: 'tutor', text: "Good choice. And what will your main focus be?" },
        { who: 'sam',   text: "We're looking at erosion, mainly — how the river reshapes its banks over time." },
        { who: 'tutor', text: "Excellent. Will you need to borrow any equipment from the department?" },
        { who: 'nadia', text: "We'll bring our own cameras, but we'd like to borrow the GPS units to map our sample points." },
        { who: 'tutor', text: "That's fine, I'll reserve them. And what do you see as the main risk?" },
        { who: 'sam',   text: "Honestly, the weather — if it rains heavily the banks get slippery and dangerous." },
        { who: 'tutor', text: "Sensible. How long will you be out in the field?" },
        { who: 'nadia', text: "Two days. We did consider a single day, but we need time for repeat measurements." },
        { who: 'tutor', text: "Let's divide the tasks. Sam, what will you take on?" },
        { who: 'sam',   text: "I'll handle measuring the river — the width, the depth, and the flow speed." },
        { who: 'tutor', text: "Good. Nadia?" },
        { who: 'nadia', text: "I'll do the interviews with local farmers about how the flooding affects their land." },
        { who: 'tutor', text: "Perfect. And I'll take care of the practical side — I'll arrange the transport to the site." },
        { who: 'nadia', text: "Great. When does the write-up need to be in?" },
        { who: 'tutor', text: "The report is due on the fifteenth of November." },
        { who: 'sam',   text: "And is there a limit on how many can come along?" },
        { who: 'tutor', text: "Yes — for safety, the maximum group size is eight students." },
        { who: 'nadia', text: "Understood. Thanks, Dr Okafor." },
      ],
      groups: [
        {
          type: 'mc',
          instructions: 'Choose the correct letter, A, B or C.',
          questions: [
            { n: 21, at: 1, text: 'Where have the students decided to go?',
              options: ['to the coast', 'to a river valley', 'to a mountain'], answer: 1, anchor: ['river valley'] },
            { n: 22, at: 3, text: 'What is the main focus of their study?',
              options: ['erosion', 'pollution', 'wildlife'], answer: 0, anchor: ['erosion'] },
            { n: 23, at: 5, text: 'What will they borrow from the department?',
              options: ['cameras', 'GPS units', 'drones'], answer: 1, anchor: ['gps units', 'gps'] },
            { n: 24, at: 7, text: 'What do they see as the main risk?',
              options: ['traffic', 'the weather', 'deep water'], answer: 1, anchor: ['weather'] },
            { n: 25, at: 9, text: 'How long will the trip last?',
              options: ['one day', 'two days', 'a week'], answer: 1, anchor: ['two days'] },
          ],
        },
        {
          type: 'matching',
          instructions: 'Who will do each task? Write A (Sam), B (Nadia) or C (Dr Okafor).',
          options: ['A — Sam', 'B — Nadia', 'C — Dr Okafor'],
          questions: [
            { n: 26, at: 11, text: 'Measuring the river',          answer: 'A', alt: ['a'], anchor: ['measuring the river', 'measuring'] },
            { n: 27, at: 13, text: 'Interviewing local farmers',   answer: 'B', alt: ['b'], anchor: ['interviews', 'interviews with local farmers'] },
            { n: 28, at: 14, text: 'Arranging the transport',      answer: 'C', alt: ['c'], anchor: ['arrange the transport', 'transport'] },
          ],
        },
        {
          type: 'form', kind: 'completion',
          formTitle: 'FIELD TRIP DETAILS · Q29–30',
          instructions: 'Write NO MORE THAN TWO WORDS AND/OR A NUMBER for each answer.',
          wordLimit: 2,
          questions: [
            { n: 29, at: 16, label: 'Report due date',      answer: '15 NOVEMBER', alt: ['fifteenth of november', 'nov 15'] },
            { n: 30, at: 18, label: 'Maximum group size',   answer: '8 STUDENTS',  alt: ['eight students', 'eight', '8'] },
          ],
        },
      ],
    },

    // ── SECTION 4 — Cours magistral monologue (note completion) ──────────────────
    {
      number: 4,
      title: 'Lecture — A Short History of Tea',
      type: 'lecture',
      runtimeType: 'form', requiredTypes: ['completion'], wordLimit: 2,
      context: 'a lecture about the history of tea',
      splitAt: null,
      formTitle: 'A SHORT HISTORY OF TEA — LECTURE NOTES · Q31–40',
      instructions: 'Write NO MORE THAN TWO WORDS AND/OR A NUMBER for each answer.',
      speakers: {
        lecturer: { voice: 'en-GB-Neural2-A', gender: 'F', accent: 'en-GB', label: 'Lecturer' },
      },
      script: [
        { who: 'lecturer', text: "Good afternoon. Today we'll follow the remarkable journey of tea, from a wild plant to the world's most popular drink after water." },
        { who: 'lecturer', text: "The tea plant is originally native to China, where it was first drunk as a medicine over two thousand years ago." },
        { who: 'lecturer', text: "For long-distance trade, the leaves were often compressed into bricks — so tightly that they were even used as a form of money." },
        { who: 'lecturer', text: "Tea first reached Europe in the sixteenth century, carried mainly by Dutch traders, rather than the Portuguese, who had focused on spices." },
        { who: 'lecturer', text: "In Britain it became fashionable at court, largely thanks to a queen — Catherine of Braganza, who made tea-drinking stylish." },
        { who: 'lecturer', text: "Because it was so popular, the government placed a heavy tax on tea, which led to widespread smuggling along the coast." },
        { who: 'lecturer', text: "Resentment at such taxes wasn't only British: in 1773, American colonists famously threw crates of tea into the harbour — the Boston Tea Party." },
        { who: 'lecturer', text: "To break China's control of supply, the British began growing tea themselves in India, which soon became the largest producer." },
        { who: 'lecturer', text: "Getting it home quickly mattered too: fast sailing ships, the tea clippers, raced each other to bring the first crop of the season to London." },
        { who: 'lecturer', text: "The British also developed a habit of their own — adding milk, which is still how most people here take their tea." },
        { who: 'lecturer', text: "And today? The nation that drinks the most tea per person is not Britain, but Turkey, by quite a margin." },
        { who: 'lecturer', text: "So, from a Chinese medicine to a global ritual — that is the story of tea. Thank you." },
      ],
      questions: [
        { n: 31, at: 1,  label: 'Tea plant originally native to',        answer: 'CHINA',   alt: ['china'] },
        { n: 32, at: 2,  label: 'For trade, leaves compressed into',      answer: 'BRICKS',  alt: ['brick'] },
        { n: 33, at: 3,  label: 'Brought to Europe mainly by ___ traders', answer: 'DUTCH',  alt: ['the dutch'] },
        { n: 34, at: 4,  label: 'Made fashionable in Britain by a',        answer: 'QUEEN',   alt: ['a queen'] },
        { n: 35, at: 5,  label: 'Heavy ___ led to smuggling',             answer: 'TAX',     alt: ['taxes', 'a tax'] },
        { n: 36, at: 6,  label: 'The 1773 protest: the Boston Tea ___',    answer: 'PARTY',   alt: ['tea party'] },
        { n: 37, at: 7,  label: 'British grew tea themselves in',          answer: 'INDIA',   alt: ['india'] },
        { n: 38, at: 8,  label: 'Fast tea ___ raced to London',           answer: 'SHIPS',   alt: ['clippers', 'tea clippers', 'sailing ships'] },
        { n: 39, at: 9,  label: 'Distinctive British habit: adding',       answer: 'MILK',    alt: ['milk'] },
        { n: 40, at: 10, label: 'Country drinking most tea per person',    answer: 'TURKEY',  alt: ['turkey'] },
      ],
    },
  ],
};

if (typeof module !== 'undefined') module.exports = TEST03;
