// ParrotTalk — SOURCE D'AUTORING Listening Test 04 (v2 — simulateur fidèle).
// Contenu 100 % original. Même chaîne v2 (narration de marque gravée, exemple P1,
// coupures S1–3, Partie 4 d'un trait, cue sheets). Aucune mention de marque tierce
// dans l'audio. Calibrage difficulté +10 % comme le Test 02 (leviers dosés).

const TEST04 = {
  id: 'test04',
  title: 'Listening Test 04',
  accentPool: ['en-GB', 'en-AU', 'en-US'],
  narratorVoice: 'en-GB-Neural2-D',
  intro: 'Welcome to the ParrotTalk listening test, the smartest way to train your ears. You will hear a number of different recordings, and you will hear each one only once.',
  sections: [

    // ── SECTION 1 — Dialogue transactionnel (form completion + épellation) ──────
    {
      number: 1,
      title: 'Oakwood Student Lettings — Room Enquiry',
      type: 'form',
      runtimeType: 'form', requiredTypes: ['completion'], wordLimit: 3,
      context: 'a conversation between a student and a lettings agent about renting a room',
      splitAt: 12,
      example: {
        lines: [
          { who: 'agent',   text: "Oakwood Student Lettings, how can I help?" },
          { who: 'student', text: "Hi, I'm looking to rent a room for the coming academic year." },
        ],
        answer: "The caller wants to rent a room, so 'room' has been written in the space. Now we shall begin.",
      },
      formTitle: 'OAKWOOD STUDENT LETTINGS — ENQUIRY FORM · Q1–10',
      instructions: 'Write NO MORE THAN THREE WORDS AND/OR A NUMBER for each answer.',
      speakers: {
        agent:   { voice: 'en-GB-Neural2-A', gender: 'F', accent: 'en-GB', label: 'Lettings agent' },
        student: { voice: 'en-US-Neural2-D', gender: 'M', accent: 'en-US', label: 'Student' },
      },
      script: [
        { who: 'agent',   text: "Good morning, Oakwood Student Lettings, this is Rachel. How can I help?" },
        { who: 'student', text: "Hi, I'm looking for a room for the coming year, and I've got a few questions." },
        { who: 'agent',   text: "Happy to help. Could I take your surname first?" },
        { who: 'student', text: "It's Ashworth — A. S. H. W. O. R. T. H." },
        { who: 'agent',   text: "Thank you. What sort of room are you after? We have shared rooms and en-suites." },
        { who: 'student', text: "I was thinking a shared room — actually, make it an en-suite; I'd like my own bathroom." },
        { who: 'agent',   text: "Good choice. The shared rooms are a hundred and twenty a week; the en-suites are a hundred and forty." },
        { who: 'student', text: "A hundred and forty is okay." },
        { who: 'agent',   text: "And when would you need it from?" },
        { who: 'student', text: "The tenth of September — sorry, the first of September." },
        { who: 'agent',   text: "The first of September. And how long would you like the tenancy?" },
        { who: 'student', text: "A full year — well, nine months, just the academic year." },
        { who: 'agent',   text: "Nine months, noted. There's a deposit of two hundred pounds to hold the room." },
        { who: 'student', text: "Two hundred, that's fine. Are the bills included?" },
        { who: 'agent',   text: "Most are — heating, water, internet. The only one you pay separately is electricity." },
        { who: 'student', text: "Good to know. And how far is it from campus?" },
        { who: 'agent',   text: "It's close — about fifteen minutes on foot, or five by bike." },
        { who: 'student', text: "That's handy. How should I get in touch to arrange a viewing?" },
        { who: 'agent',   text: "You can call, but email is best — we reply the same day." },
        { who: 'student', text: "I'll email, then." },
        { who: 'agent',   text: "Great. Your enquiry reference is OW3480 — do quote it when you write." },
        { who: 'student', text: "OW3480 — thanks, Rachel!" },
      ],
      questions: [
        { n: 1,  at: 3,  label: 'Surname',                    answer: 'ASHWORTH',   alt: ['ashworth'] },
        { n: 2,  at: 5,  label: 'Type of room chosen',        answer: 'EN-SUITE',   alt: ['ensuite', 'en suite'] },
        { n: 3,  at: 7,  label: 'Weekly rent (£)',            answer: '140',        alt: ['£140', 'a hundred and forty', '140 pounds'] },
        { n: 4,  at: 9,  label: 'Move-in date',               answer: '1 SEPTEMBER', alt: ['first of september', '1 sept', 'sept 1'] },
        { n: 5,  at: 11, label: 'Length of tenancy',          answer: '9 MONTHS',   alt: ['nine months'] },
        { n: 6,  at: 12, label: 'Deposit (£)',                answer: '200',        alt: ['£200', 'two hundred', '200 pounds'] },
        { n: 7,  at: 14, label: 'Bill paid separately',       answer: 'ELECTRICITY', alt: ['electric'] },
        { n: 8,  at: 16, label: 'Distance to campus on foot', answer: '15 MINUTES', alt: ['fifteen minutes'] },
        { n: 9,  at: 18, label: 'Preferred way to make contact', answer: 'EMAIL',   alt: ['by email', 'e-mail'] },
        { n: 10, at: 20, label: 'Enquiry reference',          answer: 'OW3480',     alt: ['ow 3480'] },
      ],
    },

    // ── SECTION 2 — Monologue (map ×5 + MCQ ×2 + completion ×3) ──────────────────
    {
      number: 2,
      title: 'Northgate Library — New Member Tour',
      type: 'mixed',
      runtimeType: 'mixed', requiredTypes: ['maplabel', 'mc', 'completion'],
      context: 'a talk by a librarian showing new members around a library',
      splitAt: 7,
      speakers: {
        lib: { voice: 'en-AU-Neural2-A', gender: 'F', accent: 'en-AU', label: 'Librarian' },
      },
      script: [
        { who: 'lib', text: "Hi everyone, welcome to Northgate Library. I'm Kylie — let me show you around using the plan in your pack, marked A to H." },
        { who: 'lib', text: "As you come in, the returns desk — where you drop off books — is at point C, straight ahead." },
        { who: 'lib', text: "The children's area, with picture books and toys, is at point F, in the bright corner on the left." },
        { who: 'lib', text: "The public computers are at point A, along the right-hand wall as you enter." },
        { who: 'lib', text: "If you need silence, the quiet study room is at point G, upstairs at the back." },
        { who: 'lib', text: "And the café — everyone asks — is at point E, sorry, point D, just past the magazines." },
        { who: 'lib', text: "Now, a few things to know as new members." },
        { who: 'lib', text: "We're open daily, and we stay open late on Thursdays, until eight — the other evenings we close at six." },
        { who: 'lib', text: "You can borrow up to twelve items at once — books, DVDs, audiobooks — though DVDs are limited to three." },
        { who: 'lib', text: "To join, just bring some ID — a driving licence or passport is fine." },
        { who: 'lib', text: "Do return books on time; there's a small fine of twenty pence a day on anything overdue." },
        { who: 'lib', text: "And bring the little ones on Saturday mornings — we run a free storytime session at half past ten." },
        { who: 'lib', text: "Right — enjoy exploring, and do ask if you get lost!" },
      ],
      groups: [
        {
          type: 'form', kind: 'maplabel',
          formTitle: 'NORTHGATE LIBRARY — PLAN · Q11–15',
          instructions: 'Label the plan below. Write the correct letter, A–H, next to each area.',
          questions: [
            { n: 11, at: 1, label: 'Returns desk',     answer: 'C', alt: ['c'] },
            { n: 12, at: 2, label: "Children's area",   answer: 'F', alt: ['f'] },
            { n: 13, at: 3, label: 'Computers',        answer: 'A', alt: ['a'] },
            { n: 14, at: 4, label: 'Quiet study room', answer: 'G', alt: ['g'] },
            { n: 15, at: 5, label: 'Café',             answer: 'D', alt: ['d'] },
          ],
        },
        {
          type: 'mc',
          instructions: 'Choose the correct letter, A, B or C.',
          questions: [
            { n: 16, at: 7, text: 'On which day does the library open late?',
              options: ['Tuesday', 'Thursday', 'Saturday'], answer: 1, anchor: ['thursdays', 'thursday'] },
            { n: 17, at: 8, text: 'How many items can members borrow at once?',
              options: ['three', 'eight', 'twelve'], answer: 2, anchor: ['twelve'] },
          ],
        },
        {
          type: 'form', kind: 'completion',
          formTitle: 'MEMBERSHIP NOTES · Q18–20',
          instructions: 'Write NO MORE THAN TWO WORDS AND/OR A NUMBER for each answer.',
          wordLimit: 2,
          questions: [
            { n: 18, at: 9,  label: 'What new members must bring to join', answer: 'ID',        alt: ['identification', 'some id'] },
            { n: 19, at: 10, label: 'Daily charge for an overdue book',    answer: '20P',       alt: ['20 pence', 'twenty pence'] },
            { n: 20, at: 11, label: 'Free event on Saturday mornings',     answer: 'STORYTIME', alt: ['story time', 'storytelling'] },
          ],
        },
      ],
    },

    // ── SECTION 3 — Discussion (MCQ ×3 + matching ×4 + completion ×3), débit +5 % ─
    {
      number: 3,
      title: 'Tutorial — Campus Café Market Research',
      type: 'discussion',
      runtimeType: 'mixed', requiredTypes: ['mc', 'matching', 'completion'],
      context: 'a discussion between a tutor and two students about a market-research project for a campus café',
      splitAt: 10,
      rate: 1.05,
      speakers: {
        tutor: { voice: 'en-GB-Neural2-B', gender: 'M', accent: 'en-GB', label: 'Dr Bennett (tutor)' },
        leila: { voice: 'en-US-Neural2-E', gender: 'F', accent: 'en-US', label: 'Leila (student)' },
        jack:  { voice: 'en-AU-Neural2-D', gender: 'M', accent: 'en-AU', label: 'Jack (student)' },
      },
      script: [
        { who: 'tutor', text: "Right, Leila, Jack — the campus café project. Remind me of the main aim?" },
        { who: 'leila', text: "We want to help them attract more students — the café's often empty. They keep talking about cutting costs, but really it's about getting people in." },
        { who: 'tutor', text: "Good. And how will you gather your data?" },
        { who: 'jack',  text: "We first thought face-to-face interviews, but an online survey will reach far more people." },
        { who: 'tutor', text: "Sensible. What sample size are you aiming for?" },
        { who: 'leila', text: "We'd like two hundred responses — a hundred felt too few to be reliable." },
        { who: 'tutor', text: "Two hundred's ambitious, but good. Let's assign the work. Jack?" },
        { who: 'jack',  text: "I'll design the questionnaire — I've built one before." },
        { who: 'tutor', text: "Great. Leila?" },
        { who: 'leila', text: "I'll analyse the results once they come in; I'm comfortable with the statistics." },
        { who: 'tutor', text: "There's still promotion — someone has to get students to actually take part." },
        { who: 'jack',  text: "I can do that too — I'll promote the survey around campus and on social media." },
        { who: 'tutor', text: "Good. And I'll approve the questions before you send anything out, to keep it ethical." },
        { who: 'leila', text: "Makes sense. How long should the survey stay open?" },
        { who: 'tutor', text: "Keep it open for two weeks — long enough to reach your target." },
        { who: 'jack',  text: "And the report length?" },
        { who: 'tutor', text: "Around fifteen hundred words, plus your charts." },
        { who: 'leila', text: "And when's the deadline?" },
        { who: 'tutor', text: "The twentieth of March." },
        { who: 'jack',  text: "Great, thanks Dr Bennett." },
      ],
      groups: [
        {
          type: 'mc',
          instructions: 'Choose the correct letter, A, B or C.',
          questions: [
            { n: 21, at: 1, text: 'What is the main aim of the project?',
              options: ['to raise prices', 'to attract more students', 'to cut costs'], answer: 1, anchor: ['attract more students', 'attract'] },
            { n: 22, at: 3, text: 'What method will they use?',
              options: ['face-to-face interviews', 'an online survey', 'a focus group'], answer: 1, anchor: ['online survey', 'survey'] },
            { n: 23, at: 5, text: 'What sample size do they want?',
              options: ['fifty', 'one hundred', 'two hundred'], answer: 2, anchor: ['two hundred'] },
          ],
        },
        {
          type: 'matching',
          instructions: 'Who will carry out each task? Write A (Jack), B (Leila) or C (Dr Bennett).',
          options: ['A — Jack', 'B — Leila', 'C — Dr Bennett'],
          questions: [
            { n: 24, at: 7,  text: 'Designing the questionnaire', answer: 'A', alt: ['a'], anchor: ['design the questionnaire', 'questionnaire'] },
            { n: 25, at: 9,  text: 'Analysing the results',       answer: 'B', alt: ['b'], anchor: ['analyse the results', 'analyse'] },
            { n: 26, at: 11, text: 'Promoting the survey',        answer: 'A', alt: ['a'], anchor: ['promote the survey', 'promote'] },
            { n: 27, at: 12, text: 'Approving the questions',     answer: 'C', alt: ['c'], anchor: ['approve the questions', 'approve'] },
          ],
        },
        {
          type: 'form', kind: 'completion',
          formTitle: 'PROJECT DETAILS · Q28–30',
          instructions: 'Write NO MORE THAN TWO WORDS AND/OR A NUMBER for each answer.',
          wordLimit: 2,
          questions: [
            { n: 28, at: 14, label: 'The survey stays open for', answer: 'TWO WEEKS',  alt: ['2 weeks'] },
            { n: 29, at: 16, label: 'Length of the report',      answer: '1500 WORDS', alt: ['fifteen hundred words', '1500'] },
            { n: 30, at: 18, label: 'Submission deadline',       answer: '20 MARCH',   alt: ['twentieth of march', 'march 20'] },
          ],
        },
      ],
    },

    // ── SECTION 4 — Cours magistral monologue (note completion, paraphrase) ──────
    {
      number: 4,
      title: 'Lecture — A Short History of the Bicycle',
      type: 'lecture',
      runtimeType: 'form', requiredTypes: ['completion'], wordLimit: 2,
      context: 'a lecture about the history of the bicycle',
      splitAt: null,
      formTitle: 'A SHORT HISTORY OF THE BICYCLE — LECTURE NOTES · Q31–40',
      instructions: 'Write NO MORE THAN TWO WORDS AND/OR A NUMBER for each answer.',
      speakers: {
        lecturer: { voice: 'en-GB-Neural2-C', gender: 'F', accent: 'en-GB', label: 'Lecturer' },
      },
      script: [
        { who: 'lecturer', text: "Good afternoon. Today, the two-hundred-year story of the bicycle, from a wooden curiosity to a symbol of freedom." },
        { who: 'lecturer', text: "The earliest machine, from 1817, had no pedals at all — you simply pushed along the ground with your feet." },
        { who: 'lecturer', text: "The next version did have pedals, on the front wheel, but its iron frame was so uncomfortable it was nicknamed the boneshaker." },
        { who: 'lecturer', text: "Then came the model with one enormous front wheel and a tiny rear one — the penny-farthing, fast but dangerous." },
        { who: 'lecturer', text: "The real breakthrough was the safety bicycle, with two wheels of equal size and a chain drive, much like bikes today." },
        { who: 'lecturer', text: "Comfort improved dramatically with the invention of air-filled tyres, which cushioned the ride." },
        { who: 'lecturer', text: "Socially, the bicycle mattered enormously: it gave women, in particular, a new sense of freedom and independence." },
        { who: 'lecturer', text: "The great cycling boom came in the 1880s — in fact, the 1890s, when prices fell and everyone wanted one." },
        { who: 'lecturer', text: "In modern times, frames became far lighter thanks to aluminium, and later carbon fibre." },
        { who: 'lecturer', text: "Today, the most cycle-friendly city is often said to be Copenhagen, ahead even of Amsterdam." },
        { who: 'lecturer', text: "And the fastest-growing type now? The electric bike, which is bringing whole new groups onto two wheels." },
        { who: 'lecturer', text: "So, from the boneshaker to the e-bike — two centuries of reinvention. Thank you." },
      ],
      questions: [
        { n: 31, at: 1,  label: 'The 1817 machine had no',           answer: 'PEDALS',         alt: ['pedal'] },
        { n: 32, at: 2,  label: 'Rough early model was nicknamed the', answer: 'BONESHAKER',    alt: ['bone shaker'] },
        { n: 33, at: 3,  label: 'Model with one huge front wheel',    answer: 'PENNY-FARTHING', alt: ['penny farthing'] },
        { n: 34, at: 4,  label: 'The safety bicycle had two equal',   answer: 'WHEELS',         alt: ['wheel'] },
        { n: 35, at: 5,  label: 'Comfort improved thanks to air-filled', answer: 'TYRES',       alt: ['tyre', 'tires'] },
        { n: 36, at: 6,  label: 'Bicycles gave women a sense of',     answer: 'FREEDOM',        alt: ['independence'] },
        { n: 37, at: 7,  label: 'Decade of the cycling boom',         answer: '1890S',          alt: ['1890', '1890s'] },
        { n: 38, at: 8,  label: 'Modern frames made lighter using',   answer: 'ALUMINIUM',      alt: ['aluminum'] },
        { n: 39, at: 9,  label: 'Most cycle-friendly city today',     answer: 'COPENHAGEN',     alt: ['copenhagen'] },
        { n: 40, at: 10, label: 'Fastest-growing type of bike',       answer: 'ELECTRIC',       alt: ['electric bike', 'e-bike', 'e-bikes'] },
      ],
    },
  ],
};

if (typeof module !== 'undefined') module.exports = TEST04;
